# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcPANEL1(wx.Panel):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "PANEL1")
        self.PostCreate(pre)

        # Define variables for the controls
        self.name = xrc.XRCCTRL(self, "name")
        self.addr1 = xrc.XRCCTRL(self, "addr1")
        self.addr2 = xrc.XRCCTRL(self, "addr2")
        self.city = xrc.XRCCTRL(self, "city")
        self.state = xrc.XRCCTRL(self, "state")
        self.zipcode = xrc.XRCCTRL(self, "zipcode")
        self.phone = xrc.XRCCTRL(self, "phone")
        self.email = xrc.XRCCTRL(self, "email")
        self.SaveBtn = xrc.XRCCTRL(self, "SaveBtn")
        self.CancelBtn = xrc.XRCCTRL(self, "CancelBtn")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('realworld2.xrc')
