name: Deploy preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  publish-website:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build website
        uses: ./.github/actions/build-website
        if: github.event.action != 'closed'

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: output
