name: wxPyWeb Publish
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  publish-website:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build website
        uses: ./.github/actions/build-website

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.RIOBU_SSH_KEY }}
          known_hosts: ${{ secrets.RIOBU_KNOWN_HOSTS }}
          config: |
            Host wxpython-site
              HostName riobu.com
              User rbot.wxpython

      - name: Publish website
        run: |
          nikola deploy
